spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rufet45990

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    drop-first: false
    database-change-log-table: UNI_TECH_DBCHANGELOG
    database-change-log-lock-table: UNI_TECH_DBCHANGELOGLOCK

